spring:
  application:
    name: xiaojie-member
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/score?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
  logger:
    enabled: true